Using grep instead of making an ignore list

diff --git a/bin/checksum b/bin/checksum
--- a/bin/checksum
+++ b/bin/checksum
@@ -1,36 +1,28 @@
 #!/bin/sh
 
-add_ignore_list() {
-	ignore="${ignore} ! -path './$1'"
-}
-
-mk_ignore_list() {
-	ignorelist=$(mktemp)
-	sed 's/^\w\+\s\+\.\///' "$sumfile" > "$ignorelist"
-	while read -r file; do
-		add_ignore_list "$file"
-	done < "$ignorelist"
-}
-
-exist_sumfile() {
-	[ -f "$sumfile" ] && [ ! "$force" ] && [ ! "$missing" ] && {
-		echo "'$sumfile' already exists. Please specify the -m option to only add missing files or the -o option to continue."; exit 1
-	}
-}
-
-while getopts omf:i: arg; do
+while getopts omf:i:d:a: arg; do
 	case $arg in
 		f) sumfile=$OPTARG ;;
 		o) force=1 ;;
 		m) missing=1 ;;
+		a) hashalgo=$OPTARG ;;
 		i) add_ignore_list "$OPTARG" ;;
+		d) dir=$OPTARG ;;
 		\?) exit 1 ;;
 	esac
 done
-
 sumfile=${sumfile:-checksum.md5}
-add_ignore_list "$sumfile"
-exist_sumfile
+dir=${dir:-.}
+hashalgo=${hashalgo:-md5sum}
 
-[ "$missing" ] && mk_ignore_list
-eval find '.' -type f $ignore -exec md5sum '{}' + >> "$sumfile"
+[ -f "$sumfile" ] && [ ! "$force" ] && [ ! "$missing" ] && {
+	echo "'$sumfile' already exists. Please specify the -m option to only add missing files or the -o option to continue."; exit 1
+}
+
+if [ "$missing" ]; then
+	find "$dir" -type f | while read -r file; do
+		grep -qF "$file" "$sumfile" || $hashalgo "$file" >> "$sumfile"
+	done
+else
+	find "$dir" -type f -exec $hashalgo '{}' + >> "$sumfile"
+fi
