Put all error messages info case statement

diff --git a/bin/mount-sc b/bin/mount-sc
--- a/bin/mount-sc
+++ b/bin/mount-sc
@@ -3,13 +3,19 @@
 mount_dir="/mnt"
 cell_mount_dir="$HOME/cell-mount" # Only for mtp devices
 device_regex="sd[b-z]\+[0-9]*"
+success_mnt="Mounted successfully!"
+success_umnt="Unmounted successfully!"
 
-# Error handling
-no_device() { echo "No mountable devices found." ; exit 1 ; }
-no_mnt_device() { echo "No devices mounted at '$mount_dir'" ; exit 1 ; }
-no_cell_mount_dir() { echo "Mount folder not found." ; exit 1 ; }
-no_mtpfs() { echo "Simple-mtpfs not installed." ; exit 1 ; }
-no_fusermount() { echo "Fusermount not installed." ; exit 1 ; }
+errmsg() { # Error handling
+	case $1 in
+		no_device) echo "No mountable devices found.";;
+		no_mnt_device) echo "No devices mounted at '$mount_dir'";;
+		no_cell_mount_dir) echo "Mount folder not found.";;
+		no_mtpfs) echo "Simple-mtpfs not installed.";;
+		no_fusermount) echo "Fusermount not installed.";;
+	esac
+	exit 1
+}
 
 cryptsetup_checker() { [ ! "$(command -v cryptsetup)" ] &&
 	echo "Cryptsetup is not installed." &&
@@ -21,16 +27,12 @@ device_checker() {
 	[ ! -e /dev/"$device" ] && echo "Device not found." && exit 1
 }
 
-# Success messages
-success_mnt="Mounted successfully!"
-success_umnt="Unmounted successfully!"
-
 ls_mountable() { # List devices excluding sda (OS disc) and mounted devices
-		lsblk | grep -v "$mount_dir" | grep --color "$device_regex" || no_device
+		lsblk | grep -v "$mount_dir" | grep --color "$device_regex" || errmsg no_device
 }
 
 ls_mounted() { # List mounted devices
-		lsblk | grep "$mount_dir" | grep --color "$device_regex" || no_mnt_device
+		lsblk | grep "$mount_dir" | grep --color "$device_regex" || errmsg no_mnt_device
 }
 
 echo "1. Mount device"
@@ -59,16 +61,16 @@ case "$choise" in
 		sudo umount /dev/"$device" && echo "$success_umnt"
 		;;
 	3)
-		[ -d "$cell_mount_dir" ] || no_cell_mount_dir
-		command -v simple-mtpfs > /dev/null || no_mtpfs
+		[ -d "$cell_mount_dir" ] || errmsg no_cell_mount_dir
+		command -v simple-mtpfs > /dev/null || errmsg no_mtpfs
 		simple-mtpfs -l || exit 1
 		printf "Which device do you want to mount? "
 		read -r device
 		simple-mtpfs --device "$device" "$cell_mount_dir" && echo "$success_mnt" || exit 1
 		;;
 	4)
-		[ -d "$cell_mount_dir" ] || no_cell_mount_dir
-		command -v fusermount > /dev/null || no_fusermount
+		[ -d "$cell_mount_dir" ] || errmsg no_cell_mount_dir
+		command -v fusermount > /dev/null || errmsg no_fusermount
 		fusermount -u "$cell_mount_dir" && echo "$success_umnt" || exit 1
 		;;
 	5)
