Added more descriptive error messages to mount-sc

diff --git a/bin/mount-sc b/bin/mount-sc
--- a/bin/mount-sc
+++ b/bin/mount-sc
@@ -1,13 +1,20 @@
 #!/bin/sh
 
-mount_dir="$HOME/cell-mount" # Only for mtp
-device_regex="sd[b-z]\+[0-9]\+"
+mount_dir="/mnt"
+cell_mount_dir="$HOME/cell-mount" # Only for mtp devices
+device_regex="sd[b-z]\+[0-9]*"
 
 # Error handling
-no_device() { echo "Device not found." ; exit 1 ; }
-no_mount_dir() { echo "Mount folder not found." ; exit 1 ; }
+no_device() { echo "No mountable devices found." ; exit 1 ; }
+no_mnt_device() { echo "No devices mounted at '$mount_dir'" ; exit 1 ; }
+no_cell_mount_dir() { echo "Mount folder not found." ; exit 1 ; }
 no_mtpfs() { echo "Simple-mtpfs not installed." ; exit 1 ; }
 no_fusermount() { echo "Fusermount not installed." ; exit 1 ; }
+
+device_checker() {
+	[ -z "$device" ] && echo "No device given." && exit 1
+	[ ! -e /dev/"$device" ] && echo "Device not found." && exit 1
+}
 
 # Success messages
 success_mnt="Mounted successfully!"
@@ -26,30 +33,28 @@ case "$choise" in
 		lsblk | grep -v "/mnt" | grep --color "$device_regex" || no_device # List devices excluding sda (OS disc) and devices mounted at /mnt
 		printf "Which device to you want to mount? "
 		read -r device
-		[ -e /dev/"$device" ] || no_device # Check if device exists
-		[ -z "$device" ] && no_device # Make sure the input isn't empty
+		device_checker
 		sudo mount /dev/"$device" /mnt && echo "$success_mnt"
 		;;
 	2)
-		lsblk | grep "/mnt" | grep --color "$device_regex" || no_device
+		lsblk | grep "/mnt" | grep --color "$device_regex" || no_mnt_device
 		printf "Which device to you want to umount? "
 		read -r device
-		[ -e /dev/"$device" ] || no_device
-		[ -z "$device" ] && no_device
+		device_checker
 		sudo umount /dev/"$device" && echo "$success_umnt"
 		;;
 	3)
-		[ -d "$mount_dir" ] || no_mount_dir
+		[ -d "$cell_mount_dir" ] || no_cell_mount_dir
 		command -v simple-mtpfs > /dev/null || no_mtpfs
 		simple-mtpfs -l || exit 1
 		printf "Which device do you want to mount? "
 		read -r device
-		simple-mtpfs --device "$device" "$mount_dir" && echo "$success_mnt" || exit 1
+		simple-mtpfs --device "$device" "$cell_mount_dir" && echo "$success_mnt" || exit 1
 		;;
 	4)
-		[ -d "$mount_dir" ] || no_mount_dir
+		[ -d "$cell_mount_dir" ] || no_cell_mount_dir
 		command -v fusermount > /dev/null || no_fusermount
-		fusermount -u "$mount_dir" && echo "$success_umnt" || exit 1
+		fusermount -u "$cell_mount_dir" && echo "$success_umnt" || exit 1
 		;;
 	*)
 		echo "Invalid option"
