Optimized mount-sc

diff --git a/bin/mount-sc b/bin/mount-sc
--- a/bin/mount-sc
+++ b/bin/mount-sc
@@ -3,16 +3,15 @@
 mount_dir="$HOME/cell-mount" # Only for mtp
 device_regex="sd[b-z]\+[0-9]\+"
 
-# Error handeling
-no_device() { echo "Device not found" ; exit 1 ; }
-no_mount_dir() { echo "Mount folder not found" ; exit 1 ; }
-no_mtpfs() { echo "Simple-mtpfs not installed" ; exit 1 ; }
-no_fusermount() { echo "Fusermount not installed" ; exit 1 ; }
-mtp_safety_check() {
-	[ -d "$mount_dir" ] || no_mount_dir
-	command -v simple-mtpfs > /dev/null || no_mtpfs
-	command -v fusermount > /dev/null || no_fusermount
-}
+# Error handling
+no_device() { echo "Device not found." ; exit 1 ; }
+no_mount_dir() { echo "Mount folder not found." ; exit 1 ; }
+no_mtpfs() { echo "Simple-mtpfs not installed." ; exit 1 ; }
+no_fusermount() { echo "Fusermount not installed." ; exit 1 ; }
+
+# Success messages
+success_mnt="Mounted successfully!"
+success_umnt="Unmounted successfully!"
 
 echo "1. Mount device"
 echo "2. Unmount device"
@@ -29,7 +28,7 @@ case "$choise" in
 		read -r device
 		[ -e /dev/"$device" ] || no_device # Check if device exists
 		[ -z "$device" ] && no_device # Make sure the input isn't empty
-		sudo mount /dev/"$device" /mnt && echo "Device mounted at /mnt"
+		sudo mount /dev/"$device" /mnt && echo "$success_mnt"
 		;;
 	2)
 		lsblk | grep "/mnt" | grep --color "$device_regex" || no_device
@@ -37,19 +36,20 @@ case "$choise" in
 		read -r device
 		[ -e /dev/"$device" ] || no_device
 		[ -z "$device" ] && no_device
-		sudo umount /dev/"$device" && echo "Device umounted"
+		sudo umount /dev/"$device" && echo "$success_umnt"
 		;;
 	3)
-		mtp_safety_check
+		[ -d "$mount_dir" ] || no_mount_dir
+		command -v simple-mtpfs > /dev/null || no_mtpfs
 		simple-mtpfs -l || exit 1
-		echo "Which device do you want to mount?"
+		printf "Which device do you want to mount? "
 		read -r device
-		[ -z "$device" ] && no_device
-		simple-mtpfs --device "$device" "$mount_dir" && echo "Mounted successfully!" || exit 1
+		simple-mtpfs --device "$device" "$mount_dir" && echo "$success_mnt" || exit 1
 		;;
 	4)
-		mtp_safety_check
-		fusermount -u "$mount_dir" && echo "Unmounted successfully!" || exit 1
+		[ -d "$mount_dir" ] || no_mount_dir
+		command -v fusermount > /dev/null || no_fusermount
+		fusermount -u "$mount_dir" && echo "$success_umnt" || exit 1
 		;;
 	*)
 		echo "Invalid option"
